### ISSUE TITLE
.gitignore device ignore

### ISSUE THREAD

**Issue by Centurion83** [BootleggersROM/manifest#12]
Hello, I have built for marlin this firmware not to long ago, when I add my device I get a message saying my path was ignored in the gitignore file. Is something wrong with the Marlin build now?

**Comment by Call190Now** [comment]
@Centurion83

**Comment by henriquee0023** [comment]
I don't get it how gitignore is related to our manifest

**Comment by Centurion83** [comment]
This is the first time I have had this error, dont know where to start to be honest

**Comment by Centurion83** [comment]
The issue happens when I follow the manifest instructions and add my device manifest to the local manifests folder
